---
# configs/damped_magnetic.yaml
SIM:
  N_SAMPLES: 8000
  DT: 0.001
  T_FINAL: 10.0
  OMEGA_SCALE: 0.3
  OUTPUT_DIR: "./damped_magnetic/"

BODY:
  MOMENT_OF_INERTIA: [0.15, 0.25, 0.35]

SCENARIOS:
  MAGNETIC:
    ENABLED: true
    B_FIELD: [-0.10, 0.0, 0.15]
    MAGNETIC_MOMENT: [1, 0, 0]
  DAMPED:
    ENABLED: true
    DAMPING_MATRIX: [[-0.2, 0.0, 0.0],
                     [0.0, -0.2, 0.0],
                     [0.0, 0.0, -0.2]]
  DAMPED_MAGNETIC:
    ENABLED: true
    WEIGHTS: [1.0, 0.5]
